### ISSUE TITLE
 inspect element blocked on prodigy now?

### ISSUE THREAD

**Issue by Jiankun-Huang** [PatheticMustan/ProdigyMathGameHacking#102]
Can you please help. Every time when I open the dev console prodigy redirects to https://play.prodigygame.com/play. Please help.

**Comment by DaChickenKing** [comment]
Install this extension: https://chrome.google.com/webstore/detail/redirector/ocgpenflpmgnfapjedencafcfakcekcd

Redirect https://play.prodigygame.com/public/js/public-game.min.js to https://hastebin.com/raw/pucuyifawa.js
