### ISSUE TITLE
Mod Menu will not work.

### ISSUE THREAD

**Issue by Diveodile** [PatheticMustan/ProdigyMathGameHacking#103]
Will's cheat menu won't work, and the same with the old mod menu.

**Comment by DaChickenKing** [comment]
Uh, duh-

All player classes are patched. We need to re-write basically everything, and now it's time for all-out fetch request sicko mode.

**Comment by ChillandChar** [comment]
Yes, and then we will be able to use the mod menus again.

**Comment by PatheticMustan** [comment]
opening and closing the issue as a way to bump it, and notify everybody watching the repo is childish, and annoying. The hacks have been patched, serverside cheats fixed, but for a temporary period, we have new hacks! Please do not beg for any more fixes.
