### ISSUE TITLE
THE HACKS ARE PATCHED

### ISSUE THREAD

**Issue by TGE209** [PatheticMustan/ProdigyMathGameHacking#104]
Please fix the patches.

**Comment by DaChickenKing** [comment]
We know, and, by the way, it takes _time_ to fix these patches.

**Comment by ProdigyHacksDontWork** [comment]
AHHHHHHHHHHHHHHHHHHH. I HATE THESE PATCHES. DaChickenKing, please fix hacks. I depend on them

**Comment by ChillandChar** [comment]
> AHHHHHHHHHHHHHHHHHHH. I HATE THESE PATCHES. DaChickenKing, please fix hacks. I depend on them

He is right, and why? Because you are a collaborator of this repository.

**Comment by coolbot123** [comment]
Prodigy patching the hacks is our goal we regularly try to get them to notice so don't get pissy when they patch this is what we want so don't be an idiot if you want to cheat so you can rub it in your freinds faces or claim it as your own. 

But yes we are working one a console driven api and all other information can be found on our discord: https://discord.gg/9cKMgMv

Have a nice day

-yeetus

**Comment by Lumin0S-ux** [comment]
If inspect doenst work why not just use bookmark? or is that patched too?

**Comment by coolbot123** [comment]
Join the discord  for instructions please https://discord.gg/9cKMgMv

**Comment by Avn1114** [comment]
There is a way, look at the instructional video.

**Comment by TGE209** [comment]
> If inspect doenst work why not just use bookmark? or is that patched too?

Thats exactly what I used and it dosen't work.

**Comment by Avn1114** [comment]
There is a way, look at the instructional video.

**Comment by uuuuuuuu88** [comment]
what vid

**Comment by ChillandChar** [comment]
hacks do not work for https://play.prodigygame.com/

**Comment by ChillandChar** [comment]
what vid

**Comment by Diveodile** [comment]
> what vid

https://drive.google.com/file/d/1YN-6SYJSvNHv_YbmzUX603b_PYiylRKp/view

**Comment by Diveodile** [comment]
> what vid

https://drive.google.com/file/d/1YN-6SYJSvNHv_YbmzUX603b_PYiylRKp/view

**Comment by RtypeX** [comment]
do u have the .json file to import it to the Redirector?

**Comment by RtypeX** [comment]
do u have the .json file to import it to the Redirector?
