### ISSUE TITLE
WillsModMenu

### ISSUE THREAD

**Issue by ProdMaster101** [PatheticMustan/ProdigyMathGameHacking#106]
Please fix this mod menu. This is the best hack on here in my opinion!

**Comment by uuuuuuuu88** [comment]
how do u log in

**Comment by ProdMaster101** [comment]
wut?

**Comment by ProdigyHacksDontWork** [comment]
![2020-03-31 (2)](https://user-images.githubusercontent.com/62806292/78054068-59c91500-7336-11ea-8bc0-4be99edb46bb.png)

**Comment by ProdigyHacksDontWork** [comment]
New Morph Marble. I found a way to get all epic morph marbles
