### ISSUE TITLE
Prodigy Hacks are all Patched

### ISSUE THREAD

**Issue by RetroFox-Infinite** [PatheticMustan/ProdigyMathGameHacking#108]
### All Hacks are Patched

The hacks are all patched.  When you go to the console tab in "inspect element," the whole server crashes and freezes.

### Events (In Code):
`keyboard.myKeyboard.ctrl+shift+i[2]._action=openIeMenu.onClick("Console")_game.prodigy.data.getServer.getTime.kill[0]-0`

### Events (Not in Code):
`when action - [ctrl+shift+i] and [console.open], then { Prodigy.killTime }`
> Stopping the time will also crash the whole game.

**Comment by ProdigyHacksDontWork** [comment]
There is a way to make them work look on discord

**Comment by RtypeX** [comment]
do u have the .json file to import it to the Redirector?

**Comment by RtypeX** [comment]
nvm

**Comment by PatheticMustan** [comment]
Fix for opening console, make a new bookmark with the following URL:
`javascript:console=0`
Then click on the bookmarklet.
