### ISSUE TITLE
NOTHING WORKS!!!!!!!!!!

### ISSUE THREAD

**Issue by ProdMaster101** [PatheticMustan/ProdigyMathGameHacking#109]

**Comment by ProdigyHacksDontWork** [comment]
YES NOTHING WORK BRUHHHHH

**Comment by ProdigyHacksDontWork** [comment]
![2020-03-31 (2)](https://user-images.githubusercontent.com/62806292/78054176-83823c00-7336-11ea-830e-d17731a0c897.png)

**Comment by ProdigyHacksDontWork** [comment]
THIS IS A NEW HACK I FOUND. I CAN MAKE ANY PET A MORPH MARBLE

**Comment by RtypeX** [comment]
Isn't that common that nothing works, there literally issues about this.

**Comment by ProdigyHacksDontWork** [comment]
I like my new glitch :)

**Comment by RtypeX** [comment]
Lol nothing because thats the point.
