### ISSUE TITLE
What is this??

### ISSUE THREAD

**Issue by Avn1114** [PatheticMustan/ProdigyMathGameHacking#11]
I was looking through some of the `PIXI.game.prodigy.player` functions and I found this:
![Screenshot 2020-02-19 at 2 18 46 PM](https://user-images.githubusercontent.com/60945964/74867605-f5706a00-5322-11ea-8d82-3e4c65101658.png)
WHAT IS THIS?

**Comment by PatheticMustan** [comment]
Uh, I saw that a while ago.
I tried turning it on, but I still get damaged. I haven't tested it very thoroughly.
I think it might prevent you from dying. 🤔

**Comment by PatheticMustan** [comment]
So being immortal does not prevent you from dying, and is specific to each pet/player

**Comment by Avn1114** [comment]
So what does it do

**Comment by PatheticMustan** [comment]
Not sure, that's what we need to figure out. I just ignored it, since it doesn't really show any real benefit, with the hacks we already have.

**Comment by Avn1114** [comment]
Ok
