### ISSUE TITLE
Still Working New Hack (Not really a hack)

### ISSUE THREAD

**Issue by ProdigyHacksDontWork** [PatheticMustan/ProdigyMathGameHacking#110]
This is not a very helpful hack. Just lets you cruise around prodigy as any pet in morph marble form. There is no script. Just a glitch. Here's a pic:
![2020-03-31 (2)](https://user-images.githubusercontent.com/62806292/78054355-cd6b2200-7336-11ea-9cba-025607d8c0e6.png)

**Comment by ProdigyHacksDontWork** [comment]
I will try to find a way to be morph marble forever. Currently last only a few seconds like the "Morph Marble: Number One" which is a Terromite in case you didn't know

**Comment by ProdigyHacksDontWork** [comment]
Also, this only works on epics. I am going to try to create a video of how to get it. Very complicated.

**Comment by ProdigyHacksDontWork** [comment]
I am trying to find a way to make it work not only with epics, too.

**Comment by Magmischief** [comment]
Hmm, that's interesting.

**Comment by ProdigyHacksDontWork** [comment]
And.....?

**Comment by Diveodile** [comment]
> Hmm, that's interesting.

Magmischief is right, veryyyyyy interesting... I want to try it, but it takes a long time, like the arena points hack.

**Comment by ProdigyHacksDontWork** [comment]
It actually doesn't take that long. I'd say 1-2 minutes. The only problem is that the morph only lasts for a few seconds, like what I said in a earlier comment. I completed a little bit of making the morph longer but in the long run, it doesn't work.

**Comment by RtypeX** [comment]
Hmmm... I notice when I have morph of a hamster and an invisible cloak it makes me look like that if I have an epic.

**Comment by ProdigyHacksDontWork** [comment]
Oh I never thought of that. You could be like an invisible hamster.

**Comment by ProdigyHacksDontWork** [comment]
I think I can post the video today. It might not look that good because the browser where I made the video isn't something I can post directly, so I have to use xbox game bar to take a video of my video

**Comment by ProdigyHacksDontWork** [comment]
> > Hmm, that's interesting.
> 
> Magmischief is right, veryyyyyy interesting... I want to try it, but it takes a long time, like the arena points hack.

What do you mean very interesting? Also like I said, it does not take a long time. To demonstrate it, though, it takes a while.

**Comment by Diveodile** [comment]
> > > Hmm, that's interesting.
> > 
> > 
> > Magmischief is right, veryyyyyy interesting... I want to try it, but it takes a long time, like the arena points hack.
> 
> What do you mean very interesting? Also like I said, it does not take a long time. To demonstrate it, though, it takes a while.

Ohhhhhhhhhhhhhhhhhhhhh!

**Comment by Diveodile** [comment]
> It actually doesn't take that long. I'd say 1-2 minutes. The only problem is that the morph only lasts for a few seconds, like what I said in a earlier comment. I completed a little bit of making the morph longer but in the long run, it doesn't work.

Hmmmmm...

**Comment by illuminate-whitehathacker** [comment]
> > Hmm, that's interesting.
> 
> Magmischief is right, veryyyyyy interesting... I want to try it, but it takes a long time, like the arena points hack.

Is the arena points patched and how did it work

**Comment by ProdigyHacksDontWork** [comment]
Step 7: 
Do my first 5 steps again. When you rejoin prodigy, you will look like your epic, but only for a few seconds.

**Comment by RtypeX** [comment]
do u have the .json file to import it to the Redirector?

**Comment by ProdigyHacksDontWork** [comment]
What does that have to do with my glitch?

**Comment by Diveodile** [comment]
This Github user called BigHex662 needs the .json file to import it to the redirector.

**Comment by ProdigyHacksDontWork** [comment]
I put it way down deep in the My school knows about this..... Issue

**Comment by Diveodile** [comment]
Oh shi...

**Comment by Robo-Ren** [comment]
Guys can someone hack my acc and get me all gear and level up my pets please I try it by my self but it won't let me do it

**Comment by PatheticMustan** [comment]
We now have actual hacks.

**Comment by Robo-ren** [comment]
Could u send me some

**Comment by Robo-ren** [comment]
Codes

**Comment by PatheticMustan** [comment]
https://github.com/PatheticMustan/ProdigyMathGameHacking/blob/master/HowToHack.md
