### ISSUE TITLE
The OLD Prodigy is back!

### ISSUE THREAD

**Issue by Diveodile** [PatheticMustan/ProdigyMathGameHacking#111]
The link to the old Prodigy: http://hedgehogstew.today/prodigyclassic/1-30-0.html
But only offline mode, because if you try to make or log in to an account it will not work.

**Comment by ProdigyHacksDontWork** [comment]
WHAT THE HECK IS THAT PRODIGY? Do hacks still work on it?

**Comment by ProdigyHacksDontWork** [comment]
The graphics are terrible. I don't even care if you can get the Trialmaster's Garb from Wheel of Wonder

**Comment by ProdigyHacksDontWork** [comment]
Can delete this issue, please. Do we really need to be focusing on Old Prodigy?

**Comment by Diveodile** [comment]
Sorry!
