### ISSUE TITLE
Does anyone have the .json file to import it to the Redirector?

### ISSUE THREAD

**Issue by Diveodile** [PatheticMustan/ProdigyMathGameHacking#113]
I need the .json file to import it in the Redirector.

**Comment by BigHex662** [comment]
I need the .json file to import it in the Redirector.

**Comment by BigHex662** [comment]
I need the .json file to import it in the Redirector.

**Comment by BigHex662** [comment]
I need the .json file to import it in the Redirector.

**Comment by BigHex662** [comment]
please please please wah wah wah wah wah wah wah!!!

**Comment by RtypeX** [comment]
ikr i can't find it ;-;

**Comment by PatheticMustan** [comment]
you don't need redirector anymore, just make a bookmarklet with the URL as:
```
javascript:console=0
```
