### ISSUE TITLE
Trialmaster' gear

### ISSUE THREAD

**Issue by Robo-Ren** [PatheticMustan/ProdigyMathGameHacking#114]
Hello does anyone has a hack for I could get the trialmaster gear?

**Comment by Diveodile** [comment]
Can you please delete this issue? Because we had a hack for the Trailmaster's Gear, but it got patched. And we don't need to be focusing on the Trialmaster's Gear. We are focusing on bringing the hacks back.

**Comment by Robo-Ren** [comment]
Oh ok my bad I will delete the issue

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Robo-Ren** [comment]
So there is no hacks?

**Comment by Diveodile** [comment]
As the home page said, "The Prodigy hacks are not accessible. Please remain patient."

**Comment by Diveodile** [comment]
> So there is no hacks?

Yes, unfortunately!

**Comment by Robo-Ren** [comment]
There is Hacks?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Diveodile** [comment]
There is. But all of them have been patched.

**Comment by Robo-Ren** [comment]
Oh what does patched means?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Diveodile** [comment]
Patched means, things will or are safe on something.

**Comment by Diveodile** [comment]
It also means they have been, archived.

**Comment by Robo-Ren** [comment]
Oh ok

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Robo-Ren** [comment]
Why😭

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Robo-Ren** [comment]
Hello did u guys bring any hacks back?

**Comment by PatheticMustan** [comment]
@Robo-Ren https://github.com/PatheticMustan/ProdigyMathGameHacking/blob/master/Items/Everything.js
