### ISSUE TITLE
my school knows about this....

### ISSUE THREAD

**Issue by lil-sket** [PatheticMustan/ProdigyMathGameHacking#115]
I told 1 friend about it, then word spread faster than the coronavirus

**Comment by RtypeX** [comment]
oh sh-

**Comment by Diveodile** [comment]
HOLY FU...

**Comment by Diveodile** [comment]
Scratch that, do not close this issue, let's tell the collaborators of this repository and everyone else that hacks Prodigy.

**Comment by Avn1114** [comment]
Lol that's not a big deal. Since our hacks aren't working, just deny it until the whole thing blows over.

**Comment by ProdigyHacksDontWork** [comment]
a few of my friends looked at my computer screen and went to this site.

**Comment by RtypeX** [comment]
oh

**Comment by RtypeX** [comment]
xd my friends did it before it got patched

**Comment by ProdigyHacksDontWork** [comment]
Same

**Comment by ProdigyHacksDontWork** [comment]
The hacks were also patched when I figured out how to redirect back to console.

**Comment by RtypeX** [comment]
Does anyone know the .json file for the redirector?

**Comment by RtypeX** [comment]
just asking

**Comment by ProdigyHacksDontWork** [comment]
Yes

**Comment by ProdigyHacksDontWork** [comment]
Here I'll copy it:
https://play.prodigygame.com/public/js/public-game.min.js     Put that into example URL and the Include Pattern

**Comment by RtypeX** [comment]
mk thx mate

**Comment by ProdigyHacksDontWork** [comment]
https://hastebin.com/raw/pucuyifawa.js    Put that into the Redirect To:

**Comment by RtypeX** [comment]
imma try brb

**Comment by ProdigyHacksDontWork** [comment]
And then click Show advanced options and change the checkmark in Main Window to Scripts

**Comment by RtypeX** [comment]
ok

**Comment by ProdigyHacksDontWork** [comment]
Try all that and it should work

**Comment by RtypeX** [comment]
that it?

**Comment by RtypeX** [comment]
ok

**Comment by ProdigyHacksDontWork** [comment]
Yes

**Comment by RtypeX** [comment]
oh thats what i forgot, the advacanced thing

**Comment by ProdigyHacksDontWork** [comment]
Wait so we don't want lots of people on this site?

**Comment by RtypeX** [comment]
idk? well we want prodigy to be warned that there hacks so,

**Comment by ProdigyHacksDontWork** [comment]
Oh so when lots of people use it....

**Comment by RtypeX** [comment]
mhm

**Comment by ProdigyHacksDontWork** [comment]
Oh No. Then its all my fault :(

**Comment by Avn1114** [comment]
We do, you just said it like it was a bad thing, that's all. But now that you say it, maybe it's best that we don't get as much traffic until we actually get hacks back.

**Comment by ProdigyHacksDontWork** [comment]
Well not really, but i helped the bad cause

**Comment by Diveodile** [comment]
My school does not know about this yet!

**Comment by RtypeX** [comment]
My classmates kept it a secret... maybe?

**Comment by ProdigyHacksDontWork** [comment]
Only 10 people around me know, but only 2 other people discovered website.

**Comment by RtypeX** [comment]
lol my book mark for prodigy is thick blueberry

**Comment by Diveodile** [comment]
Well, my sibling know that I hack Prodigy, but my parents don't know about it yet.

**Comment by ProdigyHacksDontWork** [comment]
To keep this site secret I had to give l hack out and other fake hacks

**Comment by RtypeX** [comment]
I do this bc I get bored and mostly have free time on online schoolwork.

**Comment by ProdigyHacksDontWork** [comment]
Luckily NONE of the hacks work, so I don't have to worry

**Comment by RtypeX** [comment]
Unless you have a redirector?

**Comment by ProdigyHacksDontWork** [comment]
None of them work, the redirector just lets you have dev tools open while u play prodigy

**Comment by RtypeX** [comment]
Ohhhhhhh

**Comment by ProdigyHacksDontWork** [comment]
So all I do is try to crash the game for everyone in my prodigy server

**Comment by ProdigyHacksDontWork** [comment]
I just spam stuff into console

**Comment by RtypeX** [comment]
I have to disable redirector for me to go on prodigy...

**Comment by ProdigyHacksDontWork** [comment]
What why?

**Comment by RtypeX** [comment]
Idk?

**Comment by ProdigyHacksDontWork** [comment]
Do you have a dell computer?

**Comment by ProdigyHacksDontWork** [comment]
A windows dell?

**Comment by RtypeX** [comment]
Mhm

**Comment by ProdigyHacksDontWork** [comment]
Ok. Then use a browser called Chromium. Or firefox and safari

**Comment by RtypeX** [comment]
Chromebook bc im working online school work

**Comment by ProdigyHacksDontWork** [comment]
Oh

**Comment by RtypeX** [comment]
i dont think im on chromium tho

**Comment by ProdigyHacksDontWork** [comment]
But you can't be on chromium if your on chromebook

**Comment by ProdigyHacksDontWork** [comment]
So I  can't help you.

**Comment by RtypeX** [comment]
oh and dang 57 comments

**Comment by RtypeX** [comment]
57 now

**Comment by ProdigyHacksDontWork** [comment]
Also your right. I have to use chromium to play prodigy

**Comment by ProdigyHacksDontWork** [comment]
Not chrome.

**Comment by ProdigyHacksDontWork** [comment]
60 now

**Comment by RtypeX** [comment]
mk

**Comment by RtypeX** [comment]
mk

**Comment by ProdigyHacksDontWork** [comment]
Who here is still in school, being able to relate to this issue?

**Comment by Diveodile** [comment]
I am still at home. Who here hates the coronavirus?
Like if you hate the coronavirus.
Dislike if you like the coronavirus.

**Comment by Magmischief** [comment]
The school is probably gonna get a hitman to kill all of us for hacking prodigy.

**Comment by RtypeX** [comment]
rlly

**Comment by RtypeX** [comment]
sheet

**Comment by Diveodile** [comment]
> The school is probably gonna get a hitman to kill all of us for hacking prodigy.

HOLY SH*T, I hope that never happens, or else I will get grounded for eternity.

**Comment by RtypeX** [comment]
true

**Comment by Diveodile** [comment]
Maybe they will punish me, with... a... KNIFE!

**Comment by RtypeX** [comment]
oh no

**Comment by RtypeX** [comment]
im playin roblox

**Comment by Diveodile** [comment]
If this happened, then I will kick their *ss*s and their p*nis with a pole.

**Comment by RtypeX** [comment]
o god

**Comment by Diveodile** [comment]
NO! NO GOD PLEASE NO! NO! NO! NOOOOOOOOOOO!

**Comment by RtypeX** [comment]
~~~~meme time~~~~

**Comment by RtypeX** [comment]
meme time

**Comment by ProdigyHacksDontWork** [comment]
I play roblox. Are you excited to get stuff during Egg Hunt?

**Comment by Diveodile** [comment]
What egg hunt?
I already got an egg from Easter 2019:
![image](https://user-images.githubusercontent.com/62447247/78699013-302d6200-78d1-11ea-85f0-43e5f13f8b7e.png)

**Comment by RtypeX** [comment]
oh yea but

**Comment by RtypeX** [comment]
that somw big eggo hugeddddddddddddddddddddd

**Comment by Diveodile** [comment]
Of course, thaz my doggo. JK, I have a dog that looks like him.

**Comment by RtypeX** [comment]
I can't delete my history on my school laptop so if I go somewhere ilke roblox its oof for me if they check history

**Comment by RtypeX** [comment]
why'd u cut him  like dat

**Comment by RtypeX** [comment]
Imma play some arsenal at 4:00 if you wanna join my username on Roblox is: NexusTheKiler 
don't Judge bc my username was spelled like that it was just that the username was token as NexusTheKiller

**Comment by RtypeX** [comment]
so the first one i said the username is is correct

**Comment by RtypeX** [comment]
and so many comments....  almost to 100

**Comment by RtypeX** [comment]
12 more

**Comment by RtypeX** [comment]
i mean't 10

**Comment by PatheticMustan** [comment]
shhhh 🤫

**Comment by RtypeX** [comment]
;-;

**Comment by Diveodile** [comment]
> I can't delete my history on my school laptop so if I go somewhere ilke roblox its oof for me if they check history

I can't delete my history, too!

**Comment by Diveodile** [comment]
> shhhh 🤫

Okay! Sorry!

**Comment by ProdigyHacksDontWork** [comment]
Hey RtypeX, I sent u a friend request in Roblox. Im nofun_nosun, I think I have a yt vid somewhere out there. You doing the egg hunt?

**Comment by ProdigyHacksDontWork** [comment]
Wait are you NexusTheKiller or NexusTheKillers because it doesn't look like you were on a 4 pm.

**Comment by ProdigyHacksDontWork** [comment]
Ok you are probably my first guess because the other one, NexusTheKiller_s_ hasn't been online for 2 years

**Comment by RtypeX** [comment]
NexusTheKiler

**Comment by ProdigyHacksDontWork** [comment]
Ok i just friended you

**Comment by RtypeX** [comment]
mk

**Comment by ProdigyHacksDontWork** [comment]
Can you accept?

**Comment by RtypeX** [comment]
damm so many friend request

**Comment by RtypeX** [comment]
what does ur avatar look like

**Comment by ProdigyHacksDontWork** [comment]
I am nofun_nosun

**Comment by ProdigyHacksDontWork** [comment]
I look like an egg

**Comment by ProdigyHacksDontWork** [comment]
Well my head is an egg

**Comment by RtypeX** [comment]
follow me so i can look and find ur acc theres like 200 pages of friend request

**Comment by ProdigyHacksDontWork** [comment]
Ok

**Comment by ProdigyHacksDontWork** [comment]
I followed you

**Comment by RtypeX** [comment]
friended u

**Comment by ProdigyHacksDontWork** [comment]
kk let me check

**Comment by RtypeX** [comment]
i dont do egg hunt for some reason

**Comment by ProdigyHacksDontWork** [comment]
Oh.... Well I've friended you.

**Comment by RtypeX** [comment]
i made robloxs games btw

**Comment by ProdigyHacksDontWork** [comment]
I will look at them

**Comment by RtypeX** [comment]
they acctually work like the sim

**Comment by RtypeX** [comment]
i got like 81 place visits from friends and sis and brother

**Comment by ProdigyHacksDontWork** [comment]
I played all of them. They are ok

**Comment by ProdigyHacksDontWork** [comment]
I'd join you but I have to start on my next video
