### ISSUE TITLE
We will start deleting our old comments in craftershaft's Gist.

### ISSUE THREAD

**Issue by Diveodile** [PatheticMustan/ProdigyMathGameHacking#116]
You all know the ProdigyGame Master Bookmarklet that craftershaft made. Well, it has so many comments that every time I go to this Gist it shows a picture of a Unicorn, so we will delete all the old comments in that Gist, so it loads faster again.

**Comment by RtypeX** [comment]
mk

**Comment by ProdigyHacksDontWork** [comment]
Yes, my friend copied one of the PIXI.prodigy hacks and found Gist. He prob has at least 50 comments on it.

**Comment by Diveodile** [comment]
Who is your friend?

**Comment by ProdigyHacksDontWork** [comment]
That is confidential. I am not at liberty to divulge that information

**Comment by Diveodile** [comment]
My bad.
