### ISSUE TITLE
Fill this form out.

### ISSUE THREAD

**Issue by Diveodile** [PatheticMustan/ProdigyMathGameHacking#119]
https://docs.google.com/forms/d/e/1FAIpQLSeI5855yar_lFgRx65Gewt6-H8DCNNFk2DIl696jXEI9QFVCg/viewform?usp=sf_link
--------------------------------------------------------
Issue hours:
Everyday: 10:00 A.M. - 8:00 P.M.

**Comment by PatheticMustan** [comment]
either keep it open, or keep it closed, what are you doing?

**Comment by Diveodile** [comment]
Umm...

**Comment by Diveodile** [comment]
Sorry?

**Comment by RtypeX** [comment]
uhh i completed it bruh

**Comment by Diveodile** [comment]
Okay, I saw your responses!

**Comment by BIGBOI-bit** [comment]
The hacks r not working

**Comment by Diveodile** [comment]
I know! Like Avn1114, "Hacks are patched for the, like 30th time."

**Comment by BIGBOI-bit** [comment]
I'm 47 how old are you guys?

**Comment by Diveodile** [comment]
You are what?!?!?!?!?!?!?!?!?!

**Comment by BIGBOI-bit** [comment]
I just started middle school(don't judge)

**Comment by BIGBOI-bit** [comment]
Im just kidding im only 12 bro

**Comment by ProdigyHacksDontWork** [comment]
I dont think im going to answer this form because you want to know some private info.

**Comment by Diveodile** [comment]
> I dont think im going to answer this form because you want to know some private info.

No, I promise I will not. I just want to know people more. I am not a real hacker. I promise.

**Comment by Diveodile** [comment]
> Im just kidding im only 12 bro

Oh, I am 11 years old.

**Comment by RtypeX** [comment]
im 11 bro

**Comment by Diveodile** [comment]
Wait... what?

**Comment by RtypeX** [comment]
what?

**Comment by Diveodile** [comment]
I am 11 years old too!

**Comment by PatheticMustan** [comment]
Most of the people who view this repository are underage children. Not only was it not actually made by any of the staff, but it's asking some really invasive questions.

```
Type your Github or real name (first and last). *
When is your birthday?
How much have you hacked Prodigy?
When did you join Github?
What was your first Gist about?
Do you have a YouTube channel?
What school do you go to?
Do you have an email?
If you said Yes, what is your email?
Do you have a Discord?
If you have a Discord server, what is the link or your Discord username?
What device do you use? (Part 1)
What device do you use? (Part 2) Ex: Windows, Android
Do you use the Bookmarklet site?
What search engine do you use?
```

I understand these questions were not made with malicious intent, but the questions are asking for information that should be private.
It's also annoying that you opened and closed the issue, many times, for no apparent reason. Not only is it annoying, BUT IT SENDS AN EMAIL AND A NOTIFICATION LITERALLY EVERYBODY WHO WATCHES THE REPOSITORY. I even warned you not to do it again. Please do not make another issue asking for personal details.
