### ISSUE TITLE
Found new hack!

### ISSUE THREAD

**Issue by bruh5000** [PatheticMustan/ProdigyMathGameHacking#12]
i found a new hack
all wepons:
`PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":1});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":2});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":3});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":4});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":5});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":6});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":7});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":8});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":9});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":10});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":11});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":12});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":13});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":14});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":15});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":16});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":17});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":18});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":19});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":20});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":21});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":22});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":23});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":24});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":25});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":26});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":27});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":28});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":29});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":30});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":31});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":32});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":33});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":34});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":35});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":36});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":37});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":38});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":39});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":40});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":41});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":42});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":43});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":44});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":45});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":46});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":47});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":48});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":49});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":50});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":51});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":52});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":53});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":54});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":55});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":56});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":57});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":58});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":59});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":60});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":61});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":62});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":63});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":64});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":65});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":66});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":67});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":68});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":69});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":70});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":71});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":72});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":73});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":74});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":75});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":76});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":77});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":78});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":79});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":80});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":81});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":82});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":83});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":84});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":85});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":86});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":87});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":88});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":89});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":90});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":91});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":92});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":93});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":94});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":95});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":96});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":97});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":98});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":99});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":100});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":101});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":102});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":103});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":104});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":105});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":106});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":107});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":108});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":109});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":110});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":111});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":112});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":113});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":114});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":115});
PIXI.game.prodigy.player.backpack.data.weapon.push({"N":1,"ID":116});`

**Comment by Avn1114** [comment]
Sorry, but we already have an all weapons hack. Check https://github.com/PatheticMustan/ProdigyMathGameHacking/blob/master/hacks/InfiniteGear.js

**Comment by PatheticMustan** [comment]
Actually I'm not sure that's a duplicate hack... Let me test it out.

**Comment by PatheticMustan** [comment]
Nevermind, @Avn1114 is right. I'm impressed at how good all these hacks are. :|
