### ISSUE TITLE
Somthing important to add.

### ISSUE THREAD

**Issue by TGE209** [PatheticMustan/ProdigyMathGameHacking#121]
This isin't that important but can you add a hack that you can get all buddies in prodigy?
Do this if you have time.

**Comment by PatheticMustan** [comment]
I'll keep it in mind. Note that all hacks are regularly patched, so the hacks we're about to release will probably be patched VERY VERY soon.

**Comment by RtypeX** [comment]
Very true!

**Comment by Diveodile** [comment]
You are right, I could not find the "Get all Buddies" hack.
I need it for my little brother and cousin.

**Comment by ProdigyHacksDontWork** [comment]
So are the new hacks out?

**Comment by scvdss** [comment]
Guys can u fix membership it is not working an d fosill and gold plls fix

**Comment by scvdss** [comment]
Hey guys if   u need buudies just do  99 conjur boxes and then open it until u get a buddy once u got 1 u are going to get wayyyy more.

**Comment by TGE209** [comment]
I mean the the epic buddies

**Comment by scvdss** [comment]
ohh the big hex and stuuff

**Comment by ProdigyHacksDontWork** [comment]
Yeh i have a morph marble glitch to get any epic/other buddy that is also a pet as a morph marble now successfully works for at least one minute. (Luna and Florafox aren't working because they are not big enough and Magmischief only works for a few seconds)

**Comment by PatheticMustan** [comment]
Everything.js has all buddies
