### ISSUE TITLE
> `PIXI.game.prodigy.debugMisc.getAllPets();` Gives all pets

### ISSUE THREAD

**Issue by scvdss** [PatheticMustan/ProdigyMathGameHacking#123]
> `PIXI.game.prodigy.debugMisc.getAllPets();` Gives all pets

 Yea I kinda hate that command cause I accidently typed in 10000 instead of 100 and my game crashed. THE LAG WAS SO HORRIBLE

_Originally posted by @TGE209 in https://github.com/PatheticMustan/ProdigyMathGameHacking/issues/67#issuecomment-605549102_

**Comment by scvdss** [comment]
NO the get all pets dont work

**Comment by RtypeX** [comment]
It's like "SIKE, got 'em"

**Comment by ProdigyHacksDontWork** [comment]
So all hacks still not working?

**Comment by Avn1114** [comment]
Read the README.md

**Comment by scvdss** [comment]
u guys then changed it

**Comment by Diveodile** [comment]
https://gist.github.com/Diveodile/05c8734e616f4a423334dc8a92d343c4

**Comment by ProdigyCookie** [comment]
How can we get all the pets in prodigy??

**Comment by PatheticMustan** [comment]
Pretty sure WCM has a button that says "get all pets". Please don't necro threads ;-;

**Comment by ProdigyCookie** [comment]
Umm ok ;-;
