### ISSUE TITLE
Can u guys fix membership because it is still not working and 1 bill gold is not and all fossils please fix this

### ISSUE THREAD

**Issue by scvdss** [PatheticMustan/ProdigyMathGameHacking#124]

**Comment by scvdss** [comment]
Guys sorry for disturbing and i am realyy happy i did the  infinite  cunjure boxes  becouse I got so much house stuff and BUDDIES!!!!!.  and i got more 
![Screenshot 2020-04-08 at 2 25 45 PM](https://user-images.githubusercontent.com/45647098/78835338-deeea280-79a4-11ea-8a1f-bad5339fe2a6.png)
![Screenshot 2020-04-08 at 2 25 38 PM](https://user-images.githubusercontent.com/45647098/78835342-e01fcf80-79a4-11ea-8c24-45cdb218d4dd.png)

**Comment by Diveodile** [comment]
> Guys sorry for disturbing and i am realyy happy i did the infinite cunjure boxes becouse I got so much house stuff and BUDDIES!!!!!. and i got more
> ![Screenshot 2020-04-08 at 2 25 45 PM](https://user-images.githubusercontent.com/45647098/78835338-deeea280-79a4-11ea-8a1f-bad5339fe2a6.png)
> ![Screenshot 2020-04-08 at 2 25 38 PM](https://user-images.githubusercontent.com/45647098/78835342-e01fcf80-79a4-11ea-8c24-45cdb218d4dd.png)

It's okay. But can you please close these issues?

**Comment by RtypeX** [comment]
i think i battled u just two seconds ago
