### ISSUE TITLE
i need help with prodigy hacks

### ISSUE THREAD

**Issue by prodigyhacker0** [PatheticMustan/ProdigyMathGameHacking#126]
so i want to get invincibility right now okay i click on it says this okay,
 change game to Phaser.GAMES[0].state.states.Login._gameObj im like what, so i go to prodigy math game and login, 
then i go to console then this pops up, Error 404 This page doesn't exist.
Try logging in again. then im like what prodigy beat the system now i cant hack so please show me how to hack prodigy in the new update show me a tutorial

**Comment by PatheticMustan** [comment]
https://drive.google.com/file/d/1qlqIlB9URPvUMq40gf9c8s0zDS2a8MTY/view
