### ISSUE TITLE
Update Invincibility.js

### ISSUE THREAD

**Issue by FelixN0324** [PatheticMustan/ProdigyMathGameHacking#130]
Phaser.GAMES[0].state.states.Login._gameObj.battle.constructor.MOD_DEFAULTS.invincible=true

to: ------>        temp2.battle.constructor.MOD_DEFAULTS.invincible=true

**Comment by Avn1114** [comment]
If you've tested this, sure. Next time make a pull reuqest

**Comment by FelixN0324** [comment]
Yes, I've tested it.

**Comment by Robo-Ren** [comment]
Hello can someone hack my account for me because I really don't know

**Comment by Robo-Ren** [comment]
Or can someone tell me how to do it

**Comment by TNThacker2015** [comment]
Don't use temp2, use temp1.object.n.c[0].exports.a.prodigy

**Comment by Robo-Ren** [comment]
Ok but i don't know how to put codes

**Comment by ProdigyHacksDontWork** [comment]
Does tit work?

**Comment by Robo-ren** [comment]
What?

**Comment by PatheticMustan** [comment]
"tit" isn't a thing, I think you're referring to "it", which controls membership. If you set `it` to true, it should temporarily set membership to true.
