### ISSUE TITLE
HAPPY EASTER!

### ISSUE THREAD

**Issue by Diveodile** [PatheticMustan/ProdigyMathGameHacking#131]
![EGGDOG](https://user-images.githubusercontent.com/62447247/79073958-8de9f180-7cb7-11ea-90bc-45b96b8cf30c.jpeg)
This issue will be closed after Easter Monday!

**Comment by Avn1114** [comment]
Um, I don't think we need this...

**Comment by Diveodile** [comment]
Sorry!
