### ISSUE TITLE
A strange Hack

### ISSUE THREAD

**Issue by FelixN0324** [PatheticMustan/ProdigyMathGameHacking#138]
Does anyone know what this hack does?

temp2.MOD_DEFAULTS = true

**Comment by Magmischief** [comment]
@FelixN0324 hack my acc plz

**Comment by Magmischief** [comment]
> Does anyone know what this hack does?
> 
> temp2.MOD_DEFAULTS = true

Enables Mod Defaults i guess

**Comment by FelixN0324** [comment]
Sure, I'll need the username and password. No harm will be done.

**Comment by FelixN0324** [comment]
Right, but it shows up nothing.

**Comment by Magmischief** [comment]
Its probaly an empty function.

**Comment by Magmischief** [comment]
> Sure, I'll need the username and password. No harm will be done.

All i want is all pets, then just make them lvl 100.

**Comment by Magmischief** [comment]
Tell me when your ready.

**Comment by Magmischief** [comment]
@FelixN0324

**Comment by FelixN0324** [comment]
I'm ready

**Comment by Magmischief** [comment]
Okay

**Comment by Magmischief** [comment]
User: ElijahM9405
Pass: spoon21

**Comment by Magmischief** [comment]
@FelixN0324 tell me when you got it

**Comment by Magmischief** [comment]
Ima delete the message because you wont hurry up

**Comment by PatheticMustan** [comment]
The script doesn't do anything. It's a dud.
