### ISSUE TITLE
How do we change the max level cap?

### ISSUE THREAD

**Issue by Avn1114** [PatheticMustan/ProdigyMathGameHacking#14]
So I've seen videos and things where people have gotten over level 100. How do we achieve this?

**Comment by Magmischief** [comment]
its patched

**Comment by GyarGG** [comment]
i had a friend who went over level 100 through hacking, but he showed me that like a week ago. Probably has been patched, but i'm pretty sure he stayed that level ;^|

**Comment by Avn1114** [comment]
Good to know. Thanks!

**Comment by Avn1114** [comment]
Ok, thanks

**Comment by Avn1114** [comment]
If anyone finds anything/ has any ideas please let me know...

**Comment by PatheticMustan** [comment]
@Avn1114, IIRC you can just manually set your level...

**Comment by PatheticMustan** [comment]
```
PIXI.game.prodigy.player.getLevel.toString()
```
returns
```
function(){return Math.min(a.b.validateInt(this.data.level,r.a.MIN_LEVEL),r.a.MAX_LEVEL)}
```

so we can assume the level data is stored in `PIXI.game.prodigy.player.data.level`.

I wouldn't suggest increasing your level beyond 100.
```
PIXI.game.prodigy.player.data.level = 666
```

Sets it to 666, but the max level displayed is 100. I'm not exactly sure how they did it. 🤔

**Comment by Avn1114** [comment]
Ok, thx

**Comment by DaChickenKing** [comment]
Well, I changed `PIXI.game.prodigy.player.data.level`

It only showed up in a few pages, such as friends list... they  must have a value stored somewhere named something like "maxLevel"

**Comment by Avn1114** [comment]
Could we find it and possibly nullify it?

**Comment by Avn1114** [comment]
Ok, we understand that the function `setLevel`/`getLevel` was the one capping everything, so @PatheticMustan already figured out a fix to this, so this is solved.
