### ISSUE TITLE
All the hacks are disabled

### ISSUE THREAD

**Issue by FelixN0324** [PatheticMustan/ProdigyMathGameHacking#142]
Prodigy patched the temp1.object.n.c[0].exports.a.instance.prodigy hack.

![Prodigyerror](https://user-images.githubusercontent.com/63550317/79348387-f1b42a80-7f02-11ea-8e24-1d39e217786c.png)

**Comment by PatheticMustan** [comment]
https://github.com/PatheticMustan/ProdigyMathGameHacking/blob/master/HowToHack.md
