### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by Avn1114** [PatheticMustan/ProdigyMathGameHacking#2]
I'm new to Github, so idk how to comment any way other than this. I just found a new hack: conjure cubes. The script is "PIXI.game.prodigy.debugMisc.getCubes()".
Hope this helps

**Comment by Avn1114** [comment]
Oof I just figured another out, and this is probably what everyone has been looking for: level hacking.
The script is PIXI.game.prodigy.player.addStars()

**Comment by PatheticMustan** [comment]
Nice! I'll add your hacks. If you want to be seen as a collabotor, you can make a pull request, and I'll merge it!

**Comment by Avn1114** [comment]
Cool!

**Comment by Avn1114** [comment]
It isn't letting me make a pull request, because it says there is nothing to compare...

**Comment by PatheticMustan** [comment]
Just merged, I think it would be cool if you joined as a collaborator.

**Comment by Avn1114** [comment]
Same. How do you do that?

**Comment by PatheticMustan** [comment]
You should see a notification, or an email. :D

**Comment by Avn1114** [comment]
Ok, thanks!

**Comment by Avn1114** [comment]
Ok, I'm in!

**Comment by Avn1114** [comment]
Could you explain my latest issue?
