### ISSUE TITLE
Forbidden...

### ISSUE THREAD

**Issue by Avn1114** [PatheticMustan/ProdigyMathGameHacking#22]
I was looking through the source code and assets of Prodigy and came across a restricted document.
![Screenshot 2020-02-26 at 8 56 10 AM](https://user-images.githubusercontent.com/60945964/75351486-3cf07c00-5876-11ea-8dcf-f6eeccbff459.png)
I think that this is where the functions are stored, and we just don't have access. I'm not sure though.

**Comment by bruh5000** [comment]
i found out why
the 403 forbidden is saying that there is nothing in there 
you have to be specific like
`https://play.prodigygame.com/assets/1.7.7/assets/scripts/app/build/load.min.js`

![Screenshot 2020-02-26 at 10 17 41 AM](https://user-images.githubusercontent.com/44099468/75364460-6531a800-5881-11ea-8b62-cb2b36a9ffd8.png)

**Comment by Avn1114** [comment]
Ok, thanks!

**Comment by DaChickenKing** [comment]
It is also possible to have a 403 forbidden if the API declines something, but that case would only come up if there were some more details along with it.
