### ISSUE TITLE
QI, Question Interface?

### ISSUE THREAD

**Issue by PatheticMustan** [PatheticMustan/ProdigyMathGameHacking#24]
I found `QI`, I think it has to do with the questions. It's available under `window.QI`

**Comment by Avn1114** [comment]
So what can it do, exactly?

**Comment by PatheticMustan** [comment]
No idea, testing to see if there's anything interesting we can use.
You can enable logging, no idea if that's useful.
```
QI.enableLogging()
```

**Comment by Avn1114** [comment]
Okie

**Comment by DaChickenKing** [comment]
I know that without QI, Prodigy won't load correctly.

I tried teleporting somewhere while on the login screen, I found that the lack of QI stopped any battles from working. However, I fixed it by pressing "New Player", closing all menus, then teleporting.
