### ISSUE TITLE
Buddy Code can be Simplified

### ISSUE THREAD

**Issue by DaChickenKing** [PatheticMustan/ProdigyMathGameHacking#26]
The buddies code could be simplified to:
```
for (i = 0; i < 200; i++) {

  PIXI.game.prodigy.player.backpack.add("follow",i,undefined,1);

}
```
Also, you gotta stop sharing this on the main wiki. Sonic says you will get blocked for sharing the link again.

**Comment by DaChickenKing** [comment]
And do you honestly still think that I'm "not past level 30"?

**Comment by PatheticMustan** [comment]
Welcome, and I was exaggerating. I'm not trying to come up with hacks just for views, I make hacks to try to annoy Prodigy until they make at least some type of anti-cheat.

**Comment by PatheticMustan** [comment]
```javascript
PIXI.game.prodigy.player.backpack.data.follow=[];
x = PIXI.game.state.states.Boot._gameData.follow;
for (i in x) {
    PIXI.game.prodigy.player.backpack.data.follow[i] = {"ID": x[i].ID, "N": 1}
}
```

Just for clarification, `PIXI.game.state.states.Boot._gameData.follow` contains a list of all the possible followers/buddies. Since we use this list, instead of just going over 0-199, we get a list of ALL loaded buddies. If they add a new buddy (membership box, new season) `PIXI.game.state.states.Boot._gameData.follow` will be updated accordingly, so we wouldn't have to adjust our code.
It also removes the possibility of any duplicate buddies, or getting a buddy that doesn't exist.

**Comment by GyarGG** [comment]
lol
but have you tried just  asking prodigy to make an anti-cheat, or you're doing it this way because it's more fun to see whats possible at the same time?
sry for any confusion reading that

**Comment by DaChickenKing** [comment]
Alright

We should make a wiki using the GitHub Wiki feature that documents how these codes work.

**Comment by DaChickenKing** [comment]
@GyarGG I was wondering the same thing

**Comment by GyarGG** [comment]
most of the codes already mention how they work though, i don't really see the need to make it even more public

**Comment by DaChickenKing** [comment]
Well... it is helpful to know how to make more, for example.

**Comment by DaChickenKing** [comment]
I think that we should send Zendesk some of these codes if they could harm the game.

**Comment by PatheticMustan** [comment]
Sure, I'll do that.

**Comment by PatheticMustan** [comment]
Also, I'm really sorry for posting links. I wasn't trying to advertise, or anything :|

**Comment by PatheticMustan** [comment]
#8
