### ISSUE TITLE
Custom name script?

### ISSUE THREAD

**Issue by Marshadow29** [PatheticMustan/ProdigyMathGameHacking#29]
My name hasn't  been on the prodigy pre chosen names list, that's always, annoyed me. is there a  script where i can change my prodigy name?

**Comment by Avn1114** [comment]
Unfortunately, we haven't found the means to do that yet...

**Comment by Marshadow29** [comment]
There is something i found called PIXI.game.prodigy.name .

**Comment by Marshadow29** [comment]
im not sure what it does but i assume its name data

**Comment by Avn1114** [comment]
It is, but it can only show you names and change them to things approved by
prodigy, I think. But you're welcome to look!

**Comment by Marshadow29** [comment]
un related, is there a way i can choose my wizard suffix from the list that prodigy has? I want the clock work town suffix

**Comment by Avn1114** [comment]
Idk

**Comment by QWERTYUIOP-a11y** [comment]
> PIXI.game.prodigy.player.name.data.setFirstName,

>:(

**Comment by Avn1114** [comment]
Don't think that will work, because all the approved first names are
associated with a number, so it needs a number input.

**Comment by PatheticMustan** [comment]
I can probably ask prodigy to add your name... What's your first name?

**Comment by Avn1114** [comment]
Hmm... so I found a script that may be effective. I used `PIXI.game.state.states.Boot._gameData.name.push(" ")` and then set the name to the one I made using `PIXI.game.prodigy.player.appearance._name.setFirstName`. When I clicked on my profile, the result was: 
![image](https://user-images.githubusercontent.com/60945964/75704712-e6c17580-5c87-11ea-860e-5485a0e3cf36.png)

**Comment by PatheticMustan** [comment]
I'd assume it resets when you reload the page, no? Boot is refreshed every page load.

**Comment by Avn1114** [comment]
Oh, yeah, maybe.
