### ISSUE TITLE
wizard suffix name changer

### ISSUE THREAD

**Issue by Marshadow29** [PatheticMustan/ProdigyMathGameHacking#30]
PIXI.game.prodigy.player.appearance._name.nickname=(number from 1-50)
7 is the the W12-4RD

**Comment by Avn1114** [comment]
Hmm, this is interesting. Maybe you could look into the associations of
other nicknames with their numbers?

**Comment by Magmischief** [comment]
`PIXI.game.prodigy.player.appearance._name.nickname=`(number from 1-56 use the codes below to find the one you want)
PRODIGY WIZARD CODES 
1.Buccaneer
2.Captain
3.First-Mate 
4.Beard the Pirate
5.Treasure Hunter
6.Robo
7.The W12 - 4RD
8.Dancemaster
9.Bot 3000
10.The Machinist
11.The Digger
12.Surveyor
13.Excavator
14.Archaeologist
15.Saurus
16.Pilot
17.The Skyfolk
18.Cloudeater
19.Stormchaser
20., Puyoy!
21.Firelord
22.Flame Wielder
23.Pyromancer
24.Coalwalker
25.The Hottie
26.Of the Forest
27.Botanist
28.The Green
29.Forest Walker
30.Wild
31.Ice Carver
32.Frozen
33.The Snowman
34.Mountaineer Climber
35.The Cool
36.The Firedancer
37.Woodland
38.The Wild
39.Snapdragon
 40.The Firefly
41.Chef
42.Hotshot
43.Firebreather
44.Flame Dancer
45.Bolt-Head
46.The Mechanic
47.Super
48.Chill
49.Mountaineer
50.Frostbringer
51.Aquatic
52.Fishy
53.Of the Sea
54.Mer
55.Glub-Glub
56,You’re Original name

**Comment by GyarGG** [comment]
I wonder if there is a way to change the actual name itself, to something custom. Like if your actual name isn’t on the list, or something.

**Comment by Magmischief** [comment]
Maybe this?
`PIXI.game.state.states.Boot._gameData.nickname[PIXI.game.prodigy.player.name.nickname] =`

**Comment by Avn1114** [comment]
This may be of some interest: `PIXI.game.prodigy.user.nameText`

**Comment by Avn1114** [comment]
No, `PIXI.game.state.states.Boot._gameData.nickname[PIXI.game.prodigy.player.name.nickname] =` doesn't seem to work. Maybe find an alternative with the `toString` function?

**Comment by PatheticMustan** [comment]
Just a warning, I'm not entirely sure about this, but be careful.
I'll confirm this later, but I think this may break your account.
Two accounts with the same name may confuse prodigy.

**Comment by PatheticMustan** [comment]
Also, custom names are not possible. The data that IS stored is a number, which refers to an item in the list, which is reset every time you load the page.
Best case, it's just undefined. Worst case, your account breaks.
