### ISSUE TITLE
Hey can I get credit for some of my scripts?

### ISSUE THREAD

**Issue by Skipps9687** [PatheticMustan/ProdigyMathGameHacking#31]
heyo, i just wanted credit for my scripts because I see alot of people taking them without credit, and I just wanted to ask

the scripts that I made were to get all items script, get all buddies, weapons, hats, and crap. if you want more info hit me up on my discord Skipps#9687
Sorry if i come across as mean, i just wanted credit. thanks !

**Comment by Avn1114** [comment]
Um, you didn't make those. I made those. You might have also found them,
but I found the code on my own without any help.

**Comment by PatheticMustan** [comment]
@Skipps9687, we legitimately did not steal code. Any hacks in this repository you see are all made up of just plain exploring, and suggestions by others.
If we DID copy your code, you'd normally see a large dump of many hacks at once. If you look at the git history, you'll see that initially it was mostly me submitting hacks that I found.

If you really don't believe me, then you and I can chat through Discord. I'm Natsumi#0637.
