### ISSUE TITLE
Something to look into? maybe?

### ISSUE THREAD

**Issue by Lumin0S-ux** [PatheticMustan/ProdigyMathGameHacking#36]
I found this code:
PIXI.game.prodigy.debugMisc.setMyArenaLeaderboardScore

Now i dont know but maybe this could help you with research, it probably wont because im a trash coder and researcher

**Comment by Avn1114** [comment]
We've already looked into that and it's just an empty function that
somebody left by mistake, and you're doing fine with coding and
researching! Don't worry about it!
