### ISSUE TITLE
PIXI.game.prodigy.player.house?

### ISSUE THREAD

**Issue by Marshadow29** [PatheticMustan/ProdigyMathGameHacking#37]
i found this while curious about a furniture script.

**Comment by Avn1114** [comment]
I noticed that, yeah. Looking into it...

**Comment by Marshadow29** [comment]
![Annotation 2020-03-02 124143](https://user-images.githubusercontent.com/61592454/75702325-41a49e00-5c83-11ea-90d7-8a69bc5ce740.jpg)

**Comment by DaChickenKing** [comment]
I looked into it

You can add items by ID, but adding a broken ID will corrupt your house data for some reason.

**Comment by Magmischief** [comment]
> I looked into it
> 
> You can add items by ID, but adding a broken ID will corrupt your house data for some reason.

What script did you use to add furniture?
