### ISSUE TITLE
Add cosmetic folder?

### ISSUE THREAD

**Issue by Magmischief** [PatheticMustan/ProdigyMathGameHacking#38]
Hey i was wondering if we could maybe add a cosmetic folder for cosmetic hacks?

**Comment by Magmischief** [comment]
And can i transfer some of the hacks i made in the DIY folder to some of the other folders?

**Comment by PatheticMustan** [comment]
Sure!

**Comment by Magmischief** [comment]
Okay cool

**Comment by Magmischief** [comment]
How do you add folders? xd

**Comment by PatheticMustan** [comment]
Edit the filename type in "Cosmetics/" and it should automatically make a new folder.
