### ISSUE TITLE
Plagiarize 

### ISSUE THREAD

**Issue by Magmischief** [PatheticMustan/ProdigyMathGameHacking#39]
This person stole some of your scripts without giving you credit 
https://gist.github.com/Lumin0S-ux/a30a5dc810847678f6a7979a4a022bac

**Comment by Magmischief** [comment]
Just letting you know

**Comment by PatheticMustan** [comment]
In the future, maybe I should have a GUI that makes it slightly harder to steal hacks.
It wouldn't stop anybody with literally any knowledge at all, but it would definitely prevent like 90% of the people here from stealing our hacks...

**Comment by Magmischief** [comment]
> In the future, maybe I should make the code look bad on purpose to make it slightly harder to steal hacks.
> It wouldn't stop anybody with literally any knowledge at all, but it would definitely prevent like 90% of the people here from stealing our hacks...

Yeah i agree.

**Comment by Lumin0S-ux** [comment]
Im sorry i just gave the link and your name

**Comment by Lumin0S-ux** [comment]
> Im sorry i just gave the link and your name

I put the name and link

**Comment by Avn1114** [comment]
It's fine, it was just a misunderstanding from what I see
