### ISSUE TITLE
Maybe make a Mod Menu like craffter shaft did? but like not copy him?

### ISSUE THREAD

**Issue by Lumin0S-ux** [PatheticMustan/ProdigyMathGameHacking#40]

**Comment by Avn1114** [comment]
Hm... Idk

**Comment by PatheticMustan** [comment]
I don't know who Crafter Shaft is, but I was thinking about making a menu....

**Comment by Magmischief** [comment]
> I don't know who Crafter Shaft is, but I was thinking about making a menu....

https://gist.github.com/craftersshaft/28c0cd66e6bdfde13ca9a5f3440559c9

**Comment by PatheticMustan** [comment]
Maybe we should just invite that person to work with us???

**Comment by Magmischief** [comment]
> Maybe we should just invite that person to work with us???

Nah

**Comment by PatheticMustan** [comment]
It should be pretty simple, I don't think menus should be too hard...

**Comment by RubberDuck55** [comment]
Hello Just a prototype if this is going to be a thing it only has teleport and it is a little hard to see but it is just a prototype
`var style = document.createElement('style');
style.innerHTML = '.hide {display: none;}'
document.head.appendChild(style);

var div = document.createElement('div');
var id = document.createAttribute("id");
id.value = 'menu';
div.setAttributeNode(id);
id = document.createAttribute("style");
id.value = 'position: absolute; z-index: 10;'
div.setAttributeNode(id);
document.body.insertBefore(div,document.getElementById('game-wrapper'));

id = document.createElement("p");
id.innerHTML = 'Teleport';

var idea = document.createAttribute('id')
idea.value = 'tele';

id.setAttributeNode(idea);

div.appendChild(document.createElement('br'))

div.appendChild(id);


var e = document.createElement("button");
var a = document.createTextNode("Cheat Menu");
var body = document.getElementsByTagName("body");

e.appendChild(a);

a = document.createAttribute('style');
a.value = 'position: absolute; z-index: 10;'

e.setAttributeNode(a);

a = document.createAttribute('id');
a.value = 'cheatButton';

e.setAttributeNode(a);

body[0].insertBefore(e, document.getElementById('game-wrapper'));

document.getElementById("cheatButton").addEventListener("click", disp);

document.getElementById('tele').addEventListener("click", teleport);

function teleport(){
  window.addEventListener('keydown', (event) => {
    PIXI.game.prodigy.user.x=PIXI.game.input.mousePointer.position.x
PIXI.game.prodigy.user.y=PIXI.game.input.mousePointer.position.y;
});
}

function disp(){
  document.getElementById("menu").classList.toggle("hide");
}`

**Comment by Avn1114** [comment]
Awesome! Try adding more functions, and then we'll revisit that.
