### ISSUE TITLE
Weird Hack

### ISSUE THREAD

**Issue by Magmischief** [PatheticMustan/ProdigyMathGameHacking#42]
I found this hack that switches your hats extremely fast and when it finishes the game crashes
`PIXI.game.prodigy.debugMisc.automateHatSwitching(100)`

**Comment by Avn1114** [comment]
Greeeeatttt....
[image: image.png]

**Comment by Magmischief** [comment]
Best script in game.

**Comment by Diveodile** [comment]
https://gist.github.com/Diveodile/8f4b41b5181b5cdb380581de59c84f61
