### ISSUE TITLE
ARENA POINTS HACK!!!!

### ISSUE THREAD

**Issue by Magmischief** [PatheticMustan/ProdigyMathGameHacking#43]
![Screenshot 2020-03-04 at 2 59 37 PM](https://user-images.githubusercontent.com/60401027/75931020-cc72cd80-5e28-11ea-9c29-6149f11f7b00.png)

**Comment by Magmischief** [comment]
Actually now that i'm investigating more it doesn't say after you log out and it doesn't show you on the leaderboard.

**Comment by Lumin0S-ux** [comment]
what exactly was the script?

**Comment by Avn1114** [comment]
Wow. That's intriguing. I don't know if we could modify it to make it
permanent?

**Comment by Magmischief** [comment]
possibly...

**Comment by Lumin0S-ux** [comment]
> possibly...

what was the script?

**Comment by Magmischief** [comment]
Secret ;)

**Comment by Lumin0S-ux** [comment]
> Secret ;)

cmon i really wanna help figure out how to make it stay :(

**Comment by Lumin0S-ux** [comment]
Can you tell me in discord, pleeaaasssseeee :(

**Comment by GyarGG** [comment]
I think I have an idea as to what it is, I won’t say it here in case I am completely wrong, but I will test it and check back
and see if I can get it to stay, too.

**Comment by PatheticMustan** [comment]
(coughs in PIXI.game.prodigy.debugMisc.setUserRank)

**Comment by Magmischief** [comment]
BRO OMG IT WAS A SECRET

**Comment by Magmischief** [comment]
HOW COULD YOU

**Comment by PatheticMustan** [comment]
Heehee, :>
Kinda sad it doesn't persist though. It would be really funny, but also patched really quickly.

**Comment by Magmischief** [comment]
Yeah

**Comment by GyarGG** [comment]
Hey I’m still investigating another one... it’ll be a while tho probably

**Comment by Magmischief** [comment]
> Hey I’m still investigating another one... it’ll be a while tho probably
> […](#)
> Sent from my iPhone
> On Mar 4, 2020, at 8:03 PM, Magmischief ***@***.***> wrote: ﻿ Yeah — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

What is it?

**Comment by PatheticMustan** [comment]
I highly doubt it's going to be possible unless we mess around with the sockets...

**Comment by Magmischief** [comment]
Well i think this should be resoled now..

**Comment by Diveodile** [comment]
https://gist.github.com/Diveodile/8f4b41b5181b5cdb380581de59c84f61
