### ISSUE TITLE
Alternate Accounts (Alts)

### ISSUE THREAD

**Issue by iamtheone12345** [PatheticMustan/ProdigyMathGameHacking#45]

**Comment by iamtheone12345** [comment]
For the people who don't really want to hack the game themselves, we can create a huge number of hacked accounts.

**Comment by Magmischief** [comment]
Yeah i like that idea. Maybe we could add a page in the wiki for people who can't hack and let them take already made hacked accounts,

**Comment by Magmischief** [comment]
One problem though, people could abuse this and take all the accounts and delete them or steal one of the already claimed hacked accounts.

**Comment by Magmischief** [comment]
I've started this in the wiki.
