### ISSUE TITLE
Membership doesnt work anymore, and can there be a hack for member for 1 month?

### ISSUE THREAD

**Issue by Antlxrs** [PatheticMustan/ProdigyMathGameHacking#47]

**Comment by Avn1114** [comment]
The member hack was patched. Now put PIXI.game.prodigy.player.it=true

**Comment by uuuuuuuu88** [comment]
thx

**Comment by iamtheone12345** [comment]
New Bookmarklet: javascript:(function()%7BPIXI.game.prodigy.player.it%3Dtrue%7D)()%3B

**Comment by PatheticMustan** [comment]
Hmm, maybe we can automate some things. Imagine using puppeteer to spam accounts, heehee

**Comment by Avn1114** [comment]
Omg, if we did that, Prodigy would probably make an anti cheat
