### ISSUE TITLE
How to change level cap on pets 

### ISSUE THREAD

**Issue by uuuuuuuu88** [PatheticMustan/ProdigyMathGameHacking#49]
Can we?

**Comment by Avn1114** [comment]
I've tried, but it doesn't seem possible rn

**Comment by uuuuuuuu88** [comment]
ok

**Comment by uuuuuuuu88** [comment]
thx for responding

**Comment by uuuuuuuu88** [comment]
cause i saw a vid on youtube this year on it and there pets were level 1000

**Comment by Avn1114** [comment]
Huh. We'll look into it, but they could have photoshopped it.

**Comment by uuuuuuuu88** [comment]
oh k

**Comment by uuuuuuuu88** [comment]
ill send the vid link

**Comment by uuuuuuuu88** [comment]
https://www.youtube.com/watch?v=_kxk1NhVIOM

**Comment by Lumin0S-ux** [comment]
That video is mostly likely not legit, he could have used any script hack for the pet and just photoshopped the level, if it was true he probably would have shown the process.

**Comment by Magmischief** [comment]
I saw that to. It's obviously fake

**Comment by uuuuuuuu88** [comment]
yea
