### ISSUE TITLE
Stars for pets

### ISSUE THREAD

**Issue by Avn1114** [PatheticMustan/ProdigyMathGameHacking#5]
I understand it isn't really necessary with the modifiers (MemberGod.js), but do you have any thoughts on how to level up pets using code? I thought I found something with the `PIXI.game.prodigy.debugMisc.fixPetStars` function, but I'm not sure if that's quite right. Thanks!

**Comment by PatheticMustan** [comment]
There are a few ways to do this. We can modify `PIXI.game.prodigy.data.storedMemberStars`, and use Membership to level up all our current pets, or we can modify the pets in the Kennel directly. I wouldn't recommend editing the pets directly, as it might break the game! We don't want that :|

**Comment by Avn1114** [comment]
Ight thanks

**Comment by Avn1114** [comment]
Ill look into that

**Comment by Avn1114** [comment]
Looks like `PIXI.game.prodigy.data.storedMemberStars` is undefined....

**Comment by Avn1114** [comment]
Nevermind, it worked!
