### ISSUE TITLE
I'm leaving this repo

### ISSUE THREAD

**Issue by DaChickenKing** [PatheticMustan/ProdigyMathGameHacking#50]
I believe this repository **started** with a good reason. But, it didn't end up with one. This isn't bringing any light to Prodigy, it just taught users how to hack. I am not going to develop any more personal hacks, either. All hacks I make now I will just send directly to Zendesk, and that's that. I don't want to help with this anymore, it's just not what it started out to be...

Goodbye, --DaChickenKing

**Comment by Avn1114** [comment]
You're right, we've lost sight of our goal here. Thank you for participating.
