### ISSUE TITLE
I think the Skip Tutorial function is actually a way of getting to the map at any time

### ISSUE THREAD

**Issue by RubberDuck55** [PatheticMustan/ProdigyMathGameHacking#52]
I used the skip tutorial after the tutorial and it put me on the map so i think it is away of getting to the map as well

**Comment by Magmischief** [comment]
I don't think that's very useful...

**Comment by Magmischief** [comment]
I don't think this is very useful considering we have escapeBattle.js...

**Comment by PatheticMustan** [comment]
No, thanks for reporting this. I had escapeBattle for a while, I just forgot to upload it.
I uploaded it today, so before that, this was totally valid. Thanks for submitting this!
