### ISSUE TITLE
someone made a youtube video on this repository... 

### ISSUE THREAD

**Issue by Magmischief** [PatheticMustan/ProdigyMathGameHacking#58]
https://www.youtube.com/watch?v=L-K4_2La20M

**Comment by Magmischief** [comment]
Their are probably more to.

**Comment by Avn1114** [comment]
Yah...

**Comment by Magmischief** [comment]
I thought we didn't want people making videos on this repository, has that changed now?

**Comment by Avn1114** [comment]
We never said we didn't want it...

**Comment by Magmischief** [comment]
Oh i guess i misunderstood. Sorry
