### ISSUE TITLE
Teleport Script will not show on others screens

### ISSUE THREAD

**Issue by RubberDuck55** [PatheticMustan/ProdigyMathGameHacking#59]
I noticed this and looked into a way to make you at least move on the other persons screen and i am so far unsuccessful help would be appreciated.

**Comment by N0tYing** [comment]
well consider examining the server file, it holds all online connections. 
(or look at the "walk" animation and how it shows on other screens.)

**Comment by PatheticMustan** [comment]
@N0tYing, server side code is not public, it's completely private. If it was public, we would be able to do SUPER cool things.

**Comment by N0tYing** [comment]
@PatheticMustan sorry, i meant animation files.
