### ISSUE TITLE
Not an issue but i really like the cheat menu guys!

### ISSUE THREAD

**Issue by Lumin0S-ux** [PatheticMustan/ProdigyMathGameHacking#60]
I like it cause it opens and closes unlike some people mod menus which only stay, maybe but a lot more cheats soon. Anyways its rlly good

**Comment by iamtheone12345** [comment]
Custom Chat doesn't work anymore.

**Comment by RubberDuck55** [comment]
Thanks a lot I worked really hard on it and more buttons will be coming soon

**Comment by Avn1114** [comment]
Maybe make it a javascript: function?

**Comment by RubberDuck55** [comment]
>Maybe make it a javascript: function?
What do you mean I have a bookmarklet in my latest addition(not yet approved)

**Comment by Avn1114** [comment]
Ah ok. That's what I meant. :)

**Comment by Magmischief** [comment]
Yeah the cheat menu is pretty dope, could use more hacks though.

**Comment by RubberDuck55** [comment]
It's a work in progress so more are on the way

**Comment by Magmischief** [comment]
Cool
