### ISSUE TITLE
Not an issue but this could work.

### ISSUE THREAD

**Issue by N0tYing** [PatheticMustan/ProdigyMathGameHacking#62]
ya know how 
`PIXI.game.prodigy.debugMisc.getAllPets();
`
gives you all pets right?
well replacing `getAllPets()` with a different variable such as `getAllOutfits()` could give you all outfits, armor, boots, or others. 
(i know it exists in "everything.js" but i just wanted make it a specific variable.)

**Comment by Avn1114** [comment]
Unfortunately, no. You should see an existing function in the dropdown
menu. If you don't it doesn't exist. Sorry.
