### ISSUE TITLE
movement hacks?

### ISSUE THREAD

**Issue by N0tYing** [PatheticMustan/ProdigyMathGameHacking#63]
are there any movement hacks?
(i tried `.walk` as a variable function, ill investigate.)

**Comment by RubberDuck55** [comment]
I am also investigating this in #59 where at least on the other screen it shows you walking to the location you teleported to

**Comment by RubberDuck55** [comment]
there is something called .hop function

**Comment by Magmischief** [comment]
> are there any movement hacks?
> (i tried `.walk` as a variable function, ill investigate.)

This is already a thing `PIXI.game.prodigy.debugMisc.setGameSpeed()`

**Comment by Magmischief** [comment]
> I am also investigating this in #59, trying to get it to at least on the other screen it show you walking to the location you teleported to

I don't think this is very useful since he whole reason for Teleport.js is just a way to get quickly around the map...(just my opinion)

**Comment by Avn1114** [comment]
I agree with you.
