### ISSUE TITLE
Colab Request

### ISSUE THREAD

**Issue by RubberDuck55** [PatheticMustan/ProdigyMathGameHacking#65]
Hello, I feel that, especially with updating the the cheat menu a lot, it would be nice if i could have colab status. Thanks : )

**Comment by Avn1114** [comment]
Sure. Make a new file and turn it into a pull request. I can't help you,
but @PatheticMustan can invite you if he wants to.

**Comment by RubberDuck55** [comment]
Do I have to make a new file or can i use the pull request I have submitted for an update to a file

**Comment by Avn1114** [comment]
That works too

**Comment by PatheticMustan** [comment]
I'll invite you as collaborator. Promise not to break anything?

**Comment by RubberDuck55** [comment]
I promise
