### ISSUE TITLE
audio bug

### ISSUE THREAD

**Issue by N0tYing** [PatheticMustan/ProdigyMathGameHacking#68]
i know it doesn't really matter, but computers don't play music or audio after using a hack.

**Comment by Avn1114** [comment]
I haven't experienced that. Maybe a coincidence...

**Comment by N0tYing** [comment]
yeah, maybe, i've been using .js bookmarks, i'll try console.

**Comment by RubberDuck55** [comment]
which ones exactly

**Comment by Magmischief** [comment]
Yeah i get the same thing, it occurs completely random though

**Comment by RubberDuck55** [comment]
If you look at the toString version of them I have seen some unseen side effects purposely put there, to get not only the intended result perhaps no music is one of them in certain ones.

**Comment by TehVegasPro763-22** [comment]
What?

**Comment by Diveodile** [comment]
???
![image](https://user-images.githubusercontent.com/62447247/77234415-9d788d80-6b84-11ea-8733-a19cdac48739.png)

**Comment by Diveodile** [comment]
Umm... What???

**Comment by PatheticMustan** [comment]
If you still experience the issue, please re-open
