### ISSUE TITLE
control enemies

### ISSUE THREAD

**Issue by N0tYing** [PatheticMustan/ProdigyMathGameHacking#69]
holdup:
is there a way to control enemies?
like how enemies sometimes miss, maybe that's a property or a variable? 
(this doesn't have to apply to online players)

**Comment by Avn1114** [comment]
Unfortunately, we will have to access gameConstants if we want that to
happen

**Comment by N0tYing** [comment]
and i take that constants is restricted?

**Comment by Avn1114** [comment]
ye
