### ISSUE TITLE
Custom Chat Problem

### ISSUE THREAD

**Issue by RandomGitHubUser2** [PatheticMustan/ProdigyMathGameHacking#70]
The custom chat (bookmarklet way AND console) does not work anymore for some reason. Could you please try and fix it? Thank you in advance.

**Comment by Lumin0S-ux** [comment]
Well i think that was reported to prodigy. So maybe they have patched it...

**Comment by N0tYing** [comment]
yep, they updated their css (at least i think so)

**Comment by RubberDuck55** [comment]
Probably Won't help but i figured out how to say things from the console including things in other languages 
`PIXI.game.prodigy.player.chatID`

**Comment by TNThacker2015** [comment]
the `PIXI.game.prodigy.chat` property has been removed.

**Comment by Diveodile** [comment]
WTF?
