### ISSUE TITLE
collab request 

### ISSUE THREAD

**Issue by N0tYing** [PatheticMustan/ProdigyMathGameHacking#72]
@PatheticMustan  i know I haven't found much, but I know some js and bash, plus i'm online like 24/7 ;). so i was wondering if you could add me as a collab?

**Comment by Magmischief** [comment]
I think we already have enough collaborators...

**Comment by Avn1114** [comment]
I agree, but it's @PatheticMustan's choice...

**Comment by N0tYing** [comment]
:(

**Comment by PatheticMustan** [comment]
If you can find a way to modify GameConstants, I'll add you as collaborator.

**Comment by Magmischief** [comment]
@Avn1114 that instructional video is fire

**Comment by Magmischief** [comment]
> If you can find a way to modify GameConstants, I'll add you as collaborator.

Lol

**Comment by N0tYing** [comment]
ok, deal

**Comment by Avn1114** [comment]
> @Avn1114 that instructional video is fire

Thanks :)
