### ISSUE TITLE
Furnishing hacks might be close

### ISSUE THREAD

**Issue by RubberDuck55** [PatheticMustan/ProdigyMathGameHacking#73]
I found a way to spam my house with chairs and get it to save
<img width="1440" alt="Screen Shot 2020-03-13 at 12 35 52 PM" src="https://user-images.githubusercontent.com/34989573/76641132-7805d700-6527-11ea-8713-0053583d95f4.png">

**Comment by RubberDuck55** [comment]
`window.addEventListener('keydown', (event) => {
        PIXI.game.prodigy.player.house.data.active.push({anchorY: 0, r: 0, stack: [], dx: 0, dy: -10, x: PIXI.game.input.mousePointer.position.x, y: PIXI.game.input.mousePointer.position.y, z: 0, ID: 1});
     });`

If you're interested

**Comment by Magmischief** [comment]
Do you have to manually put the chairs all around the house?

**Comment by RubberDuck55** [comment]
you can hold down the key

**Comment by N0tYing** [comment]
does this only work with chairs?

**Comment by RubberDuck55** [comment]
no the id at the end changes the item

**Comment by RubberDuck55** [comment]
Does anyone have a way to force a save

**Comment by N0tYing** [comment]
um i assume it has to do with `.player` variables or consts

**Comment by RubberDuck55** [comment]
I found this but it returns an error 
`PIXI.game.prodigy.debugMisc.savePlayer()`

**Comment by RubberDuck55** [comment]
<img width="1440" alt="Screen Shot 2020-03-13 at 2 47 57 PM" src="https://user-images.githubusercontent.com/34989573/76650778-aab8cb00-6539-11ea-872e-b8655306c1af.png">
another one

**Comment by Magmischief** [comment]
Lol

**Comment by Magmischief** [comment]
Whats the ID for the dinosaur

**Comment by RubberDuck55** [comment]
57

**Comment by RubberDuck55** [comment]
Just posted the get all furnishing

**Comment by Avn1114** [comment]
Is `PIXI.game.prodigy.player.forceSaveCharacter()` what you're looking for?

**Comment by RubberDuck55** [comment]
`PIXI.game.prodigy.player.forceSaveCharacter()` 

Didn't Seem to work like i want it to but I will investigate further

**Comment by Avn1114** [comment]
Ight

**Comment by Diveodile** [comment]
https://gist.github.com/Diveodile/8f4b41b5181b5cdb380581de59c84f61
