### ISSUE TITLE
Arena Points glitch

### ISSUE THREAD

**Issue by uuuuuuuu88** [PatheticMustan/ProdigyMathGameHacking#74]
If you are in a arena battle and click your spell and when the question pops up you turn your wifi off 
then do the question and when get back to the battle turn your wifi back on and wait a min and you win.

**Comment by uuuuuuuu88** [comment]
this will help

**Comment by uuuuuuuu88** [comment]
ok sorry

**Comment by Magmischief** [comment]
Lol i was joking its good

**Comment by PatheticMustan** [comment]
Pretty sure that's not a hack, it's probably just your opponent getting bored of you and leaving.

**Comment by Lumin0S-ux** [comment]
yah if so, then that has been around for a while cause i used to do that lmao

**Comment by kishsas** [comment]
It works

**Comment by BoredFishRE** [comment]
bro. this is legit 9 months old

**Comment by PatheticMustan** [comment]
> It works

That's not hacking, that's just being annoying to whoever's playing with you.
