### ISSUE TITLE
Invincibility Does Not Work

### ISSUE THREAD

**Issue by RubberDuck55** [PatheticMustan/ProdigyMathGameHacking#75]
It seems to just exit the battle when you try to attack

I posted this to make sure I am not just crazy

**Comment by Magmischief** [comment]
I tested it and it works completely fine...

**Comment by RubberDuck55** [comment]
Interesting

**Comment by RubberDuck55** [comment]
There was one case were it didn't work but other wise it did work

**Comment by RubberDuck55** [comment]
Closing

**Comment by RubberDuck55** [comment]
We Should look into this though it may be an issue

**Comment by Avn1114** [comment]
Yeah, that's weird
