### ISSUE TITLE
someone deleted wiki pages

### ISSUE THREAD

**Issue by Magmischief** [PatheticMustan/ProdigyMathGameHacking#76]
I was going to go work on the hack list but someone deleted the hack list page and possible research page

**Comment by Magmischief** [comment]
I guess since everyone can edit it its gonna be hard to find the culprit...

**Comment by Avn1114** [comment]
Oh, that's bad. We can;t make it an open wiki anymore then...

**Comment by Magmischief** [comment]
Yeah that sucks...

**Comment by RubberDuck55** [comment]
There should be a way to retrieve it, from the terminal but I think @PatheticMustan would have to do it or the person who deleted it, I tried and it didn't work

**Comment by Avn1114** [comment]
Yeah

**Comment by PatheticMustan** [comment]
Just made the wiki private

**Comment by Magmischief** [comment]
Kk

**Comment by PatheticMustan** [comment]
restored the wiki, it was DaChickenKing. He disagrees with my values.

**Comment by iamtheone12345** [comment]
He wouldn't let me share hacks on Fandom, either. He even deleted my hacking wiki on Fandom for no reason.

**Comment by iamtheone12345** [comment]
He wants all of the hacks for himself.
