### ISSUE TITLE
Illegal Stuff

### ISSUE THREAD

**Issue by zoobidoobi007** [PatheticMustan/ProdigyMathGameHacking#77]
It's kind of illegal to have free membership because Prodigy will stop making money if everyone gets free membership, so it's kind of like stealing.

**Comment by N0tYing** [comment]
welp, prodigy's fault it didn't improve it's security. 
(and their is a bug to get free membership without hacks)

**Comment by PatheticMustan** [comment]
yall I told them about membership two years ago

**Comment by N0tYing** [comment]
you told them to fix the bug?
