### ISSUE TITLE
Things to add to the Cheat Menu - 2

### ISSUE THREAD

**Issue by TNThacker2015** [PatheticMustan/ProdigyMathGameHacking#81]
Place suggestions for what I should add to the willsCheatMenu here.

**Comment by RubberDuck55** [comment]
Pets level 100

**Comment by NishaLalash675** [comment]
Hmm is there any possible way to save the items? every time I log out they get deleted.

**Comment by Magmischief** [comment]
> Hmm is there any possible way to save the items? every time I log out they get deleted.

battle a monster

**Comment by NishaLalash675** [comment]
I did and it still doesn't
 save for some reason

**Comment by RubberDuck55** [comment]
You should add a monster level chooser

**Comment by RubberDuck55** [comment]
Also make the inventory on E a toggle please

**Comment by Diveodile** [comment]
https://gist.github.com/Diveodile/8f4b41b5181b5cdb380581de59c84f61

**Comment by kaddisemu** [comment]
Ability to add a custom nickname

**Comment by DaChickenKing** [comment]
Authentication system. You to have to have a key that a server provides to use the cheat menu. If you want a key, ask a colloborator. You're key will be blocked if you abuse the hacks and don't follow the code of conduct.

Also, I'm still not a colloborator here. I just wanted to suggest a way to stop users from abusing other's with hacks.

**Comment by Avn1114** [comment]
That's a good idea, actually. Possibly create a passcode in a prompt and
encrypt it?

**Comment by DaChickenKing** [comment]
Yeah, okay.

**Comment by Squintt** [comment]
> Hmm is there any possible way to save the items? every time I log out they get deleted.

FORCE SAVE COMMAND IDIOT

**Comment by Diveodile** [comment]
I know it takes longer to make the set arena points hack, but can you put a get all buddies hack?

**Comment by Diveodile** [comment]
> Pets level 100

I have a friend and he needs epics and pets.

**Comment by Diveodile** [comment]
> > Pets level 100
> 
> I have a friend and he needs epics and pets.

And trialmaster's gear.

**Comment by Magmischief** [comment]
Will, i went to your cheat dashboard and clicked clear furniture and it said at the bottom Furniture Added! Simple mistake, i just wanted to let you know.

**Comment by RtypeX** [comment]
Savable membership??
