### ISSUE TITLE
I am Banned from the Discord

### ISSUE THREAD

**Issue by divinelemon** [PatheticMustan/ProdigyMathGameHacking#86]
My friend was on my computer, trying to help me with hacks and he somehow banned me from the discord. I am well over 13 (I think he said I was like 12 or whatever). 
This is very annoying as I normally need help on Hacks and I frequently use the discord.

**Comment by Avn1114** [comment]
You have to be 13 or over. Could that be the problem?

**Comment by Diveodile** [comment]
I think that is.

**Comment by PatheticMustan** [comment]
What's your username?

**Comment by CodeBreaker20** [comment]
for the past 2 days I've been something like: ihackprodigy(butifail), or I(try to)hackprodigy

**Comment by CodeBreaker20** [comment]
I am planning to hack his prodigy account next.
ill give him the worst name ever

**Comment by CodeBreaker20** [comment]
By the way im trying to change the wizard name (e.g. Magichand, or maelstromcrafter)

**Comment by PatheticMustan** [comment]
unbanned

**Comment by Diveodile** [comment]
> What's your username?

Who?

**Comment by divinelemon** [comment]
Rip I’m back on
But lol mike gave me 2 warnings after I typed:
Y
E
T
So I might still get banned

**Comment by Spritzerland** [comment]
k

**Comment by SwxtchCode** [comment]
k
