### ISSUE TITLE
I'm worried about anticheat...

### ISSUE THREAD

**Issue by kaddisemu** [PatheticMustan/ProdigyMathGameHacking#87]
I'm worried about an anticheat because of three reasons:

1. What would happen to accounts that are already hacked? Would they be reset back to level 1? That would suck if you were at level 72, for example, and started hacking. You would have to start all over again. Or would they be deleted/banned?
2. People could simply bypass anticheat by using a chrome/edge extension to turn it off.
3. This situation is unlikely, but what if Prodigy got DDOS attacked because of the anticheat addition?

**Comment by Diveodile** [comment]
Wow! I'm surprised.

**Comment by PatheticMustan** [comment]
1. No, lmao. They might be banned, depending on what hacks you use.
2. No, it's not that simple. That would take a LOT of effort.
3. No.

**Comment by Avn1114** [comment]
Lol a DDOS attack is not going to happen because someone hacked a game for
5 y.o.s...

**Comment by Magmischief** [comment]
Lmfao

**Comment by Magmischief** [comment]
OMG MY COMPUTER GOT COMPROMISED HELP

**Comment by Magmischief** [comment]
Lol i have started the prodigy epic trend, I've already seen a Diveodile, Luma, and Florafox around github.

**Comment by Diveodile** [comment]
Umm... what?

**Comment by RtypeX** [comment]
btw the anti-cheat only didn't let you inspect element and crashes the game saying on your page 


**"Not Found"**
