### ISSUE TITLE
Names

### ISSUE THREAD

**Issue by divinelemon** [PatheticMustan/ProdigyMathGameHacking#88]
I would take this to the discord but im banned :( even though im in 9th grade :(
Anyways...
I want to prank my friend back that got me banned from the discord. I want it to be (almost) unchangeable to "noobs" or semi-pros. 
Is there a way (like the advanced name change, just custom) to change a name?
This would really help. 
Thanks!

**Comment by CodeBreaker20** [comment]
also, I would like to delete my name. is this possible?
thanks!

**Comment by Diveodile** [comment]
???

**Comment by RtypeX** [comment]
uh umm?
