### ISSUE TITLE
YouTube Hacks

### ISSUE THREAD

**Issue by Diveodile** [PatheticMustan/ProdigyMathGameHacking#89]
Story: Every time I go on YouTube, my video keeps on loading and it never plays. So I need a hack for the videos to start playing.

**Comment by PatheticMustan** [comment]
This is not the place to fix that. If we were in charge of Youtube, we'd be making millions, instead of sitting in our houses hacking as a hobby ;)

**Comment by Diveodile** [comment]
My bad!
