### ISSUE TITLE
fix mod menu

### ISSUE THREAD

**Issue by prodigyhacks** [PatheticMustan/ProdigyMathGameHacking#92]
after i use it once it doesnt work after that

**Comment by Diveodile** [comment]
Yes, I figured out that the mod menu was not working correctly, so was the membership.

**Comment by Diveodile** [comment]
Now both mod menus will not work.

**Comment by DaChickenKing** [comment]
We already know, please stop making these "issues"

**Comment by awesomedude88677744** [comment]
hi do you know how to get wills cheat menu

**Comment by awesomedude88677744** [comment]
cause i dont know how to get it

**Comment by BoredFishRE** [comment]
Cheat menu is included with redirector method and extension method

**Comment by BoredFishRE** [comment]
please do not comment on old and closed issues. If you need help, join our discord, or if you can't do that, email us at support@prodigyhacking.com
