### ISSUE TITLE
Anything found on Arena Points hacks???

### ISSUE THREAD

**Issue by Lumin0S-ux** [PatheticMustan/ProdigyMathGameHacking#93]
I would like to know if anybody has found anything on arena point hacks...

**Comment by Diveodile** [comment]
> I would like to know if anybody has found anything on arena point hacks...

I know, I want like 500,000 arena points.

**Comment by PatheticMustan** [comment]
We had arena hacks posted on the github, but it takes a lot of work, and will's vps got blocked. :((
