### ISSUE TITLE
Prodigy Hacks have been patched.

### ISSUE THREAD

**Issue by Diveodile** [PatheticMustan/ProdigyMathGameHacking#94]
Important announcement: All the Prodigy Hacks have been patched for some reason. Some of us think that Prodigy patched the hacks.

**Comment by VoidXNemo** [comment]
yeah Phaser.GAMES[0] doesnt work anymore and neither does Phaser.GAMES[0].state.states.Login._gameObj.player

**Comment by illuminate-whitehathacker** [comment]
There using a sentry browser if that helps

**Comment by DaChickenKing** [comment]
`Phaser.GAMES[0].state.states.Boot._metricsManager.gameCompleteDataFactory.gameEventDataBuilder.loggedInPlayer._player`

Player still works

**Comment by QWERTYUIOP-a11y** [comment]
> Important announcement: All the Prodigy Hacks have been patched for some reason. Some of us think that Prodigy patched the hacks.

I told you the cops phone number

**Comment by QWERTYUIOP-a11y** [comment]
> Phaser.GAMES[0].state.states.Login._gameObj.player

Cops phone number: 416-808-2222

**Comment by Diveodile** [comment]
I will close this issue at 9 pm and will reopen it at 1 pm tomorrow, okay?

**Comment by illuminate-whitehathacker** [comment]
Okay

**Comment by illuminate-whitehathacker** [comment]
> `Phaser.GAMES[0].state.states.Boot._metricsManager.gameCompleteDataFactory.gameEventDataBuilder.loggedInPlayer._player`
> 
> Player still works

Rlly What codes plz answer

**Comment by VoidXNemo** [comment]
okay, now we need to find out how to do debugs and stuff like that with that prefix.

**Comment by Diveodile** [comment]
> okay, now we need to find out how to do debugs and stuff like that with that prefix.

Yes, and if that is settled, we can go back to hacking Prodigy again.

**Comment by illuminate-whitehathacker** [comment]
K thx

**Comment by VoidXNemo** [comment]
> > okay, now we need to find out how to do debugs and stuff like that with that prefix.
> 
> Yes, and if that is settled, we can go back to hacking Prodigy again.

yup.

**Comment by QWERTYUIOP-a11y** [comment]
> > > okay, now we need to find out how to do debugs and stuff like that with that prefix.
> > 
> > 
> > Yes, and if that is settled, we can go back to hacking Prodigy again.
> 
> yup.

When that is settled, I will complete shipwreck shore

**Comment by Diveodile** [comment]
I wanted to open this issue early cause I had nothing to do.

**Comment by QWERTYUIOP-a11y** [comment]
> Phaser.GAMES[0].state.states.Boot._metricsManager.gameCompleteDataFactory.gameEventDataBuilder.loggedInPlayer._player

>:(

**Comment by VoidXNemo** [comment]
it seems like Phaser.GAMES[0].state.states.Boot._metricsManager.gameCompleteDataFactory.gameEventDataBuilder.loggedInPlayer._player doesnt work anymore. I tried to do a simple command but it said, "VM287:1 Uncaught TypeError: Cannot read property 'state' of undefined
    at <anonymous>:1:17"

**Comment by PatheticMustan** [comment]
Fixed on discord, just go to #announcements

**Comment by Diveodile** [comment]
> it seems like Phaser.GAMES[0].state.states.Boot._metricsManager.gameCompleteDataFactory.gameEventDataBuilder.loggedInPlayer._player doesnt work anymore. I tried to do a simple command but it said, "VM287:1 Uncaught TypeError: Cannot read property 'state' of undefined
> at :1:17"

FUCK!

**Comment by Diveodile** [comment]
Thanks, you are our... hero!

**Comment by VoidXNemo** [comment]
Yaya!

**Comment by Diveodile** [comment]
> Yaya!

Yaya, indeed!

**Comment by QWERTYUIOP-a11y** [comment]
What is the discord server link?

**Comment by Diveodile** [comment]
![Screen Shot 2020-03-27 at 2 13 25 PM](https://user-images.githubusercontent.com/62447247/77786997-2e43e300-7035-11ea-8733-671c05a482b0.png)
